[versions]
# https://modrinth.com/mod/architectury-api/versions
architectury = "18.0.8"

# https://parchmentmc.org/docs/getting-started
parchment-minecraft = "1.21.10"
parchment = "2025.10.12"

# https://projects.neoforged.net/neoforged/neoforge
neoforge = "21.10.64"

# https://fabricmc.net/develop
fabric-loader = "0.18.4"
fabric-api = "0.138.4+1.21.10"

# https://maven.jamalam.tech/#/releases
jamlib = "1.3.5+1.21.10"
 
# https://modrinth.com/mod/accessories/versions
accessories = "1.4.3-beta+1.21.10"
accessories-mojmap = "1.4.3-beta+1.21.10-mojmap"

# https://modrinth.com/mod/modmenu/versions
modmenu = "16.0.0"

# https://modrinth.com/mod/lambdynamiclights/versions
lambdynamiclights = "4.8.7+1.21.10"

# https://modrinth.com/mod/sodium/versions
sodium = "mc1.21.10-0.7.3-fabric"

[libraries]
architectury-common = { module = "dev.architectury:architectury", version.ref = "architectury" }
architectury-fabric = { module = "dev.architectury:architectury-fabric", version.ref = "architectury" }
architectury-neoforge = { module = "dev.architectury:architectury-neoforge", version.ref = "architectury" }

neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

jamlib-common = { module = "io.github.jamalam360:jamlib", version.ref = "jamlib" }
jamlib-fabric = { module = "io.github.jamalam360:jamlib-fabric", version.ref = "jamlib" }
jamlib-neoforge = { module = "io.github.jamalam360:jamlib-neoforge", version.ref = "jamlib" }

accessories-common = { module = "io.wispforest:accessories-common", version.ref = "accessories-mojmap"  }
accessories-fabric = { module = "io.wispforest:accessories-fabric", version.ref = "accessories" }
accessories-neoforge = { module = "io.wispforest:accessories-neoforge", version.ref = "accessories" }

modmenu = { module = "maven.modrinth:modmenu", version.ref = "modmenu" }

lambdynamiclights-runtime = { module = "dev.lambdaurora.lambdynamiclights:lambdynamiclights-runtime", version.ref = "lambdynamiclights" }
lambdynamiclights-api = { module = "dev.lambdaurora.lambdynamiclights:lambdynamiclights-api", version.ref = "lambdynamiclights" }

sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
